name: Build and publish
run-name: Publishing to github pages 🚀
on: [push]
env:
  EM_VERSION: 3.1.23
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: lukka/get-cmake@latest
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Installing
        run: |
          npm install
      - name: Building
        run: |
          npm run build
      - name: Find and Replace path to rubberband-processor in example.html
        uses: jacobtomlinson/gha-find-replace@v2
        with:
         find: "../public/rubberband-processor.js"
         replace: "rubberband-processor.js"
         include: "example/index.html"
      - name: Copy rubberband-processor.js into example folder
        run: cp public/* example/
      - name: Publish example to github pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: example