name: Build and publish
run-name: Publishing to github pages 🚀
on: [push]
env:
  EM_VERSION: 3.1.23
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: lukka/get-cmake@latest
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Installing
        run: |
          npm install
      - name: List 1
        run: ls ${EMSCRIPTEN}
        env:
          EMSCRIPTEN: ${{env.EM_CACHE_FOLDER}}
      - name: List 2
        run: ls ${EMSCRIPTEN}
        env:
          EMSCRIPTEN: ${{env.EM_CACHE_FOLDER}}/emsdk-main
      - name: List 3
        run: ls ${EMSCRIPTEN}
        env:
          EMSCRIPTEN: ${{env.EM_CACHE_FOLDER}}/emsdk-main/emscripten
      - name: Building
        run: |
          npm run build
        env:
          EMSCRIPTEN: ${{env.EM_CACHE_FOLDER}}/emsdk-main/emscripten
      - run: echo "🍏 This job's status is ${{ job.status }}."
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1
